launch=gsqlite3
gsqlite3-database=/var/lib/powerdns/pdns.sqlite3
api=yes
api-key=b8acb2274c8b44cd904a6243eed2a26c
webserver=yes
webserver-address=0.0.0.0
webserver-port=8081
local-address=0.0.0.0
local-port=5353
