#!/usr/bin/env bash
# HS-Panel Installer — Environment Configuration
# Generates production .env file and writes credentials file.

HSPANEL_ENV_FILE="${HSPANEL_ENV_FILE:-/etc/hostingsignal/hostingsignal-devapi.env}"
HSPANEL_CREDS_FILE="${HSPANEL_CREDS_FILE:-/root/hspanel_credentials.txt}"

configure_env() {
  log_info "Generating production environment configuration..."

  mkdir -p "$(dirname "$HSPANEL_ENV_FILE")"
  chmod 700 "$(dirname "$HSPANEL_ENV_FILE")"

  # Derive server IP
  local server_ip
  server_ip="$(curl -fsSL --max-time 5 ifconfig.me 2>/dev/null || \
               curl -fsSL --max-time 5 icanhazip.com 2>/dev/null || \
               hostname -I 2>/dev/null | awk '{print $1}' || echo "127.0.0.1")"

  # Generate a JWT secret
  local jwt_secret
  jwt_secret="$(openssl rand -hex 32)"
  local license_key
  license_key="$(openssl rand -hex 20)"

  # Write env file
  cat > "$HSPANEL_ENV_FILE" <<ENV
# HostingSignal DevAPI — Production Environment
# Generated by hspanel installer on $(date)

# Core API
HSDEV_SECRET_KEY=${jwt_secret}
HSDEV_DEBUG=false
HSDEV_HOST=0.0.0.0
HSDEV_PORT=2087

# Database
HSDEV_DB_URL=mysql+pymysql://${MARIADB_APP_USER:-hspanel_user}:${MARIADB_APP_PASSWD:-}@localhost:3306/${MARIADB_APP_DB:-hspanel}

# License
HSDEV_LICENSE_API_KEY=${license_key}

# WHMCS (configure if using WHMCS integration)
HSDEV_WHMCS_ALLOWED_IPS=127.0.0.1

# Admin seed
HSDEV_ADMIN_USERNAME=${HSPANEL_ADMIN_USER:-admin}
HSDEV_ADMIN_PASSWORD=${HSPANEL_ADMIN_PASSWD:-}

# Panel domain
HSDEV_PUBLIC_URL=http://${server_ip}:2087

# PowerDNS API
HSDEV_PDNS_API_URL=http://127.0.0.1:${PDNS_API_PORT:-8053}
HSDEV_PDNS_API_KEY=${PDNS_API_KEY:-}

# Mail
HSDEV_MAIL_DOMAIN=${MAIL_DOMAIN:-localdomain}
ENV

  chmod 640 "$HSPANEL_ENV_FILE"
  log_success "Environment file written: $HSPANEL_ENV_FILE"

  # If panel has a generate script, run it
  local gen_script="${HSPANEL_INSTALL_DIR}/scripts/generate_production_env.sh"
  if [[ -f "$gen_script" ]]; then
    log_info "Running panel env generation script..."
    bash "$gen_script" >> "$HSPANEL_LOG_FILE" 2>&1 || \
      log_warning "Panel env script returned non-zero (may be okay)"
  fi

  _write_credentials_file "$server_ip"
}

_write_credentials_file() {
  local server_ip="$1"
  local ts
  ts="$(date)"

  cat > "$HSPANEL_CREDS_FILE" <<CREDS
╔══════════════════════════════════════════════════════════════╗
║         HostingSignal HS-Panel — Installation Credentials    ║
╚══════════════════════════════════════════════════════════════╝
Generated: ${ts}

──── Admin Access ────────────────────────────────────────────────
  Panel HTTP       http://${server_ip}:2086
  Panel HTTPS      https://${server_ip}:2087
  API              http://${server_ip}:2087
  Admin user       ${HSPANEL_ADMIN_USER:-admin}
  Admin password   ${HSPANEL_ADMIN_PASSWD:-}

──── OpenLiteSpeed ───────────────────────────────────────────────
  Admin URL        http://${server_ip}:${OLS_ADMIN_PORT:-8090}
  Admin user       ${OLS_ADMIN_USER:-admin}
  Admin password   ${OLS_ADMIN_PASSWD:-}

──── Database ────────────────────────────────────────────────────
  Name             ${MARIADB_APP_DB:-hspanel}
  User             ${MARIADB_APP_USER:-hspanel_user}
  Password         ${MARIADB_APP_PASSWD:-}
  Root password    ${MARIADB_ROOT_PASSWD:-}

──── phpMyAdmin ──────────────────────────────────────────────────
  URL              http://${server_ip}/phpmyadmin

──── Webmail ─────────────────────────────────────────────────────
  URL              http://${server_ip}/webmail

──── PowerDNS ────────────────────────────────────────────────────
  API key          ${PDNS_API_KEY:-}

──── Installation Paths ──────────────────────────────────────────
  Panel            ${HSPANEL_INSTALL_DIR:-/usr/local/hspanel}
  Logs             /var/log/hspanel_install.log
  Env file         ${HSPANEL_ENV_FILE}

KEEP THIS FILE SAFE. DO NOT COMMIT TO VERSION CONTROL.
CREDS

  chmod 600 "$HSPANEL_CREDS_FILE"
  log_success "Credentials saved: $HSPANEL_CREDS_FILE"
}
