ServerName localhost
Listen 80
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule authz_host_module modules/mod_authz_host.so
DocumentRoot /usr/local/apache2/htdocs
<Directory /usr/local/apache2/htdocs>
    AllowOverride All
    Require all granted
</Directory>
LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule dir_module modules/mod_dir.so
LoadModule alias_module modules/mod_alias.so
LoadModule rewrite_module modules/mod_rewrite.so
DirectoryIndex index.html index.php
